In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import numpy as np

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [3]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [4]:
X, Y = x_train / 255.0, y_train
X_test, Y_test= x_test / 255.0, y_test
print(f'X: {X.shape}, Y:{Y.shape}')

X: (60000, 28, 28), Y:(60000,)


In [14]:
print(f'x_test: {x_test.shape}, y_test:{y_test.shape}')

x_test: (10000, 28, 28), y_test:(10000,)


# Basic

In [20]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.optimizers import Adam

In [21]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  #tf.keras.layers.Dense(10, activation='linear')
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer=Adam(),
              loss=SparseCategoricalCrossentropy(),
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.6397 - loss: 6.9691
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8309 - loss: 0.6385
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8797 - loss: 0.4496
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.8991 - loss: 0.3644
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9133 - loss: 0.3131
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9221 - loss: 0.2809
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9264 - loss: 0.2680
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9313 - loss: 0.2508
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9337 - loss: 0.2388
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9365 - loss: 0.2349


In [16]:
y_pred= model.predict(x_test)
y_pred[0] # 확률

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step


array([6.7009387e-24, 1.0904076e-15, 1.5818227e-12, 8.5163213e-12,
       1.9591846e-13, 1.3093192e-17, 3.3141164e-33, 1.0000000e+00,
       5.4379164e-18, 2.2034062e-08], dtype=float32)

# Numerical Roundoff Error
- "categorical_crossentropy"는 데이터의 라벨이 원-핫 인코딩 된 형태의 경우 사용
- "sparse_categorical_crossentropy"는 데이터의 라벨이 Int형 일 때 사용한다.

In [22]:
model_improved = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='linear')
  #tf.keras.layers.Dense(10, activation='softmax')
])

model_improved.compile(optimizer=Adam(),
              loss=SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [13]:
model_improved.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 904us/step - accuracy: 0.6977 - loss: 7.4710
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 965us/step - accuracy: 0.8276 - loss: 0.6255
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 964us/step - accuracy: 0.8700 - loss: 0.4723
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 917us/step - accuracy: 0.8869 - loss: 0.4174
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 977us/step - accuracy: 0.8959 - loss: 0.3922
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 967us/step - accuracy: 0.9046 - loss: 0.3667
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 973us/step - accuracy: 0.9088 - loss: 0.3570
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 976us/step - accuracy: 0.9128 - loss: 0.3389
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 955us/step - accuracy: 0.9158 - loss: 0.3358
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 960us/step - accuracy: 0.9193 - loss: 0.3153


In [18]:
logits= model_improved.predict(x_test)
logits[0] # logits

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step


array([ 28.819332,  18.73995 ,  55.9586  ,  59.09836 ,  48.7058  ,
        44.961285, -85.62398 ,  83.40231 , -47.186493,  54.962757],
      dtype=float32)

In [19]:
y_pred_improved = tf.nn.softmax(logits)
y_pred_improved[0]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.9720255e-24, 8.2697686e-29, 1.2059974e-12, 2.7856491e-11,
       8.5407375e-16, 2.0196374e-17, 0.0000000e+00, 1.0000000e+00,
       0.0000000e+00, 4.4551027e-13], dtype=float32)>