In [1]:
import torch
import numpy as np

In [3]:
data= [[1,2], [3,4]]
x_data= torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [5]:
np_array= np.array(data)
print(np_array)
x_data= torch.from_numpy(np_array)
print(x_data)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [6]:
x_ones =torch.ones_like(x_data)
print(x_ones)
x_rand =torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.4751, 0.1748],
        [0.7036, 0.4903]])


In [8]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6946, 0.4861, 0.4020],
        [0.5960, 0.2161, 0.9364]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [12]:
device= 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else "cpu"
print(device)

mps


In [14]:
rand_tensor.to(device)
# row
print(rand_tensor[0])
# col
print(rand_tensor[:, 0])
# last col
print(rand_tensor[:, -1])

tensor([0.6946, 0.4861, 0.4020])
tensor([0.6946, 0.5960])
tensor([0.4020, 0.9364])


In [20]:
concat_horizontal= torch.cat([ones_tensor, zeros_tensor], dim=1)
print(concat_horizontal)

concat_vertical= torch.cat([ones_tensor, zeros_tensor], dim=0)
print(concat_vertical)
concat_vertical.size()

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


torch.Size([4, 3])

In [22]:
stack=torch.stack([ones_tensor, zeros_tensor])
print(stack)
stack.size()

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


torch.Size([2, 2, 3])

In [24]:
# 행(데이터수*행) 열 
concat_vertical= torch.cat([ones_tensor, zeros_tensor, rand_tensor], dim=0)
print(concat_vertical)
print(concat_vertical.size())

# 데이터수 행 열
stack=torch.stack([ones_tensor, zeros_tensor, rand_tensor])
print(stack)
print(stack.size())

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.6946, 0.4861, 0.4020],
        [0.5960, 0.2161, 0.9364]])
torch.Size([6, 3])
tensor([[[1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.6946, 0.4861, 0.4020],
         [0.5960, 0.2161, 0.9364]]])
torch.Size([3, 2, 3])


In [27]:
ta= torch.tensor([1,2,3])
tb= torch.tensor([1,2,3])
print(ta @ tb.T)
print(ta*tb)
print(ta.dot(tb))

tensor(14)
tensor([1, 4, 9])
tensor(14)


In [28]:
na= np.array([1,2,3])
nb= np.array([1,2,3])
print(na @ nb.T)
print(na*nb)
print(na.dot(nb))

14
[1 4 9]
14
